export GOVC_URL='https://100.80.0.2/sdk'
export GOVC_USERNAME='sekhar_d@domain.local'
export GOVC_PASSWORD='Dell@123'
export GOVC_INSECURE=true
export GOVC_Datacenter='myDC'
export GOVC_NETWORK='MyNetwork'
export GOVC_DATASTORE='ISO Library'
export GOVC_SourceDir='/home/sekhar/ISO'
export vm_name='U2210-RENBE'
export source_file='ubuntu-22.10-live-server-amd64.iso'
export extract_folder='source-files'
export SSH_USERNAME="ubuntu"
export SSH_PASSWORD="ubuntu"
